#!/bin/sh

#
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

currentBranch=$(git symbolic-ref HEAD)
reserialize=tools/ReSerialize/bin/./ReSerialize

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.
This can cause problems if you want to work with people on other platforms.
To be portable it is advisable to rename the file.
If you know what you are doing you can disable this check using:
  git config hooks.allownonascii true
EOF
	exit 1
fi

if [ "$currentBranch" = "refs/heads/master" ]; then
	echo "Not allowed to commit to master branch!"
	exit 1
else
	# Get only modified files with ttl extension
	files=$(git diff --cached --name-only --diff-filter=ACM| grep ".ttl$")
	succeed=0
	
	for file in ${files}; do
		# Validate each file using
		git show :$file | $reserialize -f -
		succeed=$((${succeed}+$?))
	done
	
	if [ ${succeed} -eq 0 ]; then
		echo "COMMIT SUCCEEDED"
	else
		echo "COMMIT FAILED. One of .ttl files is not serialized. Run ReSerialize.sh"
		exit 1
	fi
fi
