name: Generate documentation

on:
  push:
    branches:
      - otl-viewer
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout mapping rules
        uses: actions/checkout@v4
        with:
          repository: RWS-NL/airbim-mappingrule-generator
          path: airbim-mappingrule-generator
          token: ${{ secrets.RWS_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup python3
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: viewer/requirements.txt

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: viewer/documentation

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: viewer

      - name: Install NodeJS Dependencies
        run: yarn install --immutable
        working-directory: viewer/documentation

      - name: Parse mapping rules
        run: python3 bin/parse-mappings.py airbim-mappingrule-generator/mappingregels mapping.json
        working-directory: viewer

      - name: Generate documentation
        run: python3 bin/write-documentation.py .
        working-directory: viewer

      - name: Generate UTD
        run: python3 bin/write-utd.py .
        working-directory: viewer

      - name: Build docs
        run: yarn build
        working-directory: viewer/documentation

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: viewer/documentation/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
