PREFIX otl: <https://data.rws.nl/def/otl/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT 
	?ConceptURI 
	?ConceptNaam 
	?Definitie

FROM otl:graaf-kennismodel

WHERE { 
	?ConceptURI a skos:Concept ;
            skos:definition ?Definitie ;
            skos:prefLabel ?ConceptNaam .
} 